# docker compose 版本
version: '2'
# 容器配置
services:
  # zookeeper 容器
  zoo_2181:
    image: zookeeper
    ports:
      - 2181:2181
  # redis 容器
  redis_6379:
    image: redis:3.2
    ports:
      - 6379:6379
    volumes:
      - /etc/redis:/etc/redis
      - /var/redis:/var/redis
    command: redis-server /etc/redis/redis.conf
  # dubbo provider 容器
  db_provider:
    image: dubbo-provider
    ports:
      - 20880:20880
    hostname: dubbo-server
    extra_hosts:
      - dubbo-server:192.168.56.101
    command: bin/start.sh
  # dubbo consumer 容器
  db_consumer:
    image: dubbo-consumer
    ports:
      - 8080:8080
    command: java -jar app.jar